name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create .env file
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env
          echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> .env
          echo "BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "PORTFOLIO_API_TOKEN=${{ secrets.PORTFOLIO_API_TOKEN }}" >> .env
          echo "PORTFOLIO_API_URL=${{ secrets.PORTFOLIO_API_URL }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod -t ${{ secrets.CAPROVER_APP_NAME }}:latest .

      - name: Save Docker image
        run: |
          docker save ${{ secrets.CAPROVER_APP_NAME }}:latest > image.tar

      - name: Deploy to CapRover
        run: |
          curl -X POST \
            -H "X-Captain-Auth: ${{ secrets.CAPROVER_PASSWORD }}" \
            -F "sourceFile=@image.tar" \
            https://captain.${{ secrets.CAPROVER_DOMAIN }}/api/v2/user/apps/${{ secrets.CAPROVER_APP_NAME }}/deploy/
