name: Build and Deploy

on:
  push:
    branches:
      - master # ou la branche que tu utilises

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Version compatible avec Next.js 16

      - name: Create .env file
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env
          echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> .env
          echo "BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "PORTFOLIO_API_TOKEN=${{ secrets.PORTFOLIO_API_TOKEN }}" >> .env
          echo "PORTFOLIO_API_URL=${{ secrets.PORTFOLIO_API_URL }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" >> .env
          echo "GOOGLE_CLOUD_PRIVATE_KEY_ID=${{ secrets.GOOGLE_CLOUD_PRIVATE_KEY_ID }}" >> .env
          echo "GOOGLE_CLOUD_PRIVATE_KEY=${{ secrets.GOOGLE_CLOUD_PRIVATE_KEY }}" >> .env
          echo "GOOGLE_CLOUD_CLIENT_EMAIL=${{ secrets.GOOGLE_CLOUD_CLIENT_EMAIL }}" >> .env
          echo "GOOGLE_CLOUD_CLIENT_ID=${{ secrets.GOOGLE_CLOUD_CLIENT_ID }}" >> .env
          echo "GOOGLE_ANALYTICS_PROPERTY_ID=${{ secrets.GOOGLE_ANALYTICS_PROPERTY_ID }}" >> .env
          echo "GOOGLE_ANALYTICS_MEASUREMENT_ID=${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "ANALYTICS_REFRESH_INTERVAL=${{ secrets.ANALYTICS_REFRESH_INTERVAL }}" >> .env
          echo "ANALYTICS_CACHE_TTL=${{ secrets.ANALYTICS_CACHE_TTL }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build project
        env:
          SKIP_ENV_VALIDATION: true
        run: npm run build

      # Ici tu peux ajouter les étapes pour déployer si besoin
